# Generated by Django 3.2.8 on 2021-11-07 18:45

import aftn_national.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата поправки')),
                ('header_aftn_message', aftn_national.models.UpperCharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Некоректная строка отправителя', regex='[0-9]{6} \\S{8}')], verbose_name='Строка отправителя поправки формате АФТН')),
                ('aftn_message', models.CharField(blank=True, max_length=1800, verbose_name='Содержание поправки')),
            ],
            options={
                'verbose_name': 'Поправка',
                'verbose_name_plural': 'Поправки',
            },
        ),
        migrations.CreateModel(
            name='SymbolsDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national', aftn_national.models.UpperCharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='Требуется 2 символа на киррилице', regex='[а-яА-Я]{2}')], verbose_name='Обозначение')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование подразделения')),
                ('marked', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('excluded', models.BooleanField(default=False, verbose_name='Исключен')),
                ('correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aftn_national.correction', verbose_name='Поправка')),
            ],
            options={
                'verbose_name': 'Обозначение подразделений',
                'verbose_name_plural': 'Обозначение подразделений',
            },
        ),
        migrations.CreateModel(
            name='LocationIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national', aftn_national.models.UpperCharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Требуется 4 символа на киррилице', regex='[а-яА-Я]{4}')], verbose_name='Обозначение национальное')),
                ('international', aftn_national.models.UpperCharField(blank=True, max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Требуется 4 символа на латинице', regex='[a-zA-Z]{4}')], verbose_name='Обозначение международное')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Наименование пункта')),
                ('district_administration', models.CharField(max_length=200, verbose_name='Окружное управление ВТ')),
                ('marked', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('excluded', models.BooleanField(default=False, verbose_name='Исключен')),
                ('correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aftn_national.correction', verbose_name='Поправка')),
            ],
            options={
                'verbose_name': 'Обозначение местоположения',
                'verbose_name_plural': 'Обозначение местоположения',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSymbolsDepartment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('national', aftn_national.models.UpperCharField(db_index=True, max_length=2, validators=[django.core.validators.RegexValidator(message='Требуется 2 символа на киррилице', regex='[а-яА-Я]{2}')], verbose_name='Обозначение')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование подразделения')),
                ('marked', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('excluded', models.BooleanField(default=False, verbose_name='Исключен')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('correction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aftn_national.correction', verbose_name='Поправка')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Обозначение подразделений',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLocationIndicator',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('national', aftn_national.models.UpperCharField(db_index=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Требуется 4 символа на киррилице', regex='[а-яА-Я]{4}')], verbose_name='Обозначение национальное')),
                ('international', aftn_national.models.UpperCharField(blank=True, db_index=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Требуется 4 символа на латинице', regex='[a-zA-Z]{4}')], verbose_name='Обозначение международное')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Наименование пункта')),
                ('district_administration', models.CharField(max_length=200, verbose_name='Окружное управление ВТ')),
                ('marked', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('excluded', models.BooleanField(default=False, verbose_name='Исключен')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('correction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aftn_national.correction', verbose_name='Поправка')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Обозначение местоположения',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDesignatorOrg',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('national', aftn_national.models.UpperCharField(db_index=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Требуется 2-3 символа на киррилице', regex='[а-яА-Я]{2,3}')], verbose_name='Обозначение национальное')),
                ('international', aftn_national.models.UpperCharField(blank=True, db_index=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Требуется 3 символа на латинице', regex='[a-zA-Z]{3}')], verbose_name='Обозначение международное')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование предприятия')),
                ('marked', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('excluded', models.BooleanField(default=False, verbose_name='Исключен')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('correction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aftn_national.correction', verbose_name='Поправка')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aftn_national.locationindicator', verbose_name='Местоположение администрации')),
            ],
            options={
                'verbose_name': 'historical Обозначение служб или предприятий',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCorrection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата поправки')),
                ('header_aftn_message', aftn_national.models.UpperCharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Некоректная строка отправителя', regex='[0-9]{6} \\S{8}')], verbose_name='Строка отправителя поправки формате АФТН')),
                ('aftn_message', models.CharField(blank=True, max_length=1800, verbose_name='Содержание поправки')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Поправка',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DesignatorOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national', aftn_national.models.UpperCharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Требуется 2-3 символа на киррилице', regex='[а-яА-Я]{2,3}')], verbose_name='Обозначение национальное')),
                ('international', aftn_national.models.UpperCharField(blank=True, max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Требуется 3 символа на латинице', regex='[a-zA-Z]{3}')], verbose_name='Обозначение международное')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование предприятия')),
                ('marked', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('excluded', models.BooleanField(default=False, verbose_name='Исключен')),
                ('correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aftn_national.correction', verbose_name='Поправка')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aftn_national.locationindicator', verbose_name='Местоположение администрации')),
            ],
            options={
                'verbose_name': 'Обозначение служб или предприятий',
                'verbose_name_plural': 'Обозначение служб или предприятий',
            },
        ),
    ]
