# Generated by Django 3.2.8 on 2021-11-06 13:48

import backend.custommodels
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('date', models.DateField(blank=True)),
                ('header_aftn_message', backend.custommodels.UpperCharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Некоректная строка отправителя', regex='[0-9]{6} \\S{8}')])),
                ('aftn_message', models.CharField(blank=True, max_length=1800)),
                ('action_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolsDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national', backend.custommodels.UpperCharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='Требуется 2 символа на киррилице', regex='[а-яА-Я]{2}')])),
                ('name', models.CharField(max_length=200)),
                ('marked', models.BooleanField(default=False)),
                ('excluded', models.BooleanField(default=False)),
                ('action_datetime', models.DateTimeField(auto_now=True)),
                ('correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aftn_national.correction')),
            ],
        ),
        migrations.CreateModel(
            name='LocationIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national', backend.custommodels.UpperCharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Требуется 4 символа на киррилице', regex='[а-яА-Я]{4}')])),
                ('international', backend.custommodels.UpperCharField(blank=True, max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Требуется 4 символа на латинице', regex='[a-zA-Z]{4}')])),
                ('name', models.CharField(max_length=200)),
                ('district_administration', models.CharField(max_length=200)),
                ('marked', models.BooleanField(default=False)),
                ('excluded', models.BooleanField(default=False)),
                ('action_datetime', models.DateTimeField(auto_now=True)),
                ('correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aftn_national.correction')),
            ],
        ),
        migrations.CreateModel(
            name='DesignatorOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national', backend.custommodels.UpperCharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Требуется 2-3 символа на киррилице', regex='[а-яА-Я]{2,3}')])),
                ('international', backend.custommodels.UpperCharField(blank=True, max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Требуется 3 символа на латинице', regex='[a-zA-Z]{3}')])),
                ('name', models.CharField(max_length=200)),
                ('marked', models.BooleanField(default=False)),
                ('excluded', models.BooleanField(default=False)),
                ('action_datetime', models.DateTimeField(auto_now=True)),
                ('correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aftn_national.correction')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aftn_national.locationindicator')),
            ],
        ),
    ]
