# Generated by Django 3.2.8 on 2021-11-07 19:18

import aftn_national.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aftn_national', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocationindicator',
            name='international',
            field=aftn_national.models.UpperCharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Требуется 4 символа на латинице', regex='[a-zA-Z]{4}')], verbose_name='Обозначение международное'),
        ),
        migrations.AlterField(
            model_name='locationindicator',
            name='international',
            field=aftn_national.models.UpperCharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Требуется 4 символа на латинице', regex='[a-zA-Z]{4}')], verbose_name='Обозначение международное'),
        ),
    ]
