# Generated by Django 3.2.8 on 2021-11-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftn_national', '0002_auto_20211107_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='date',
            field=models.DateField(blank=True, verbose_name='Дата поправки'),
        ),
        migrations.AlterField(
            model_name='historicalcorrection',
            name='date',
            field=models.DateField(blank=True, verbose_name='Дата поправки'),
        ),
    ]
