# Generated by Django 3.2.8 on 2021-11-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftn_national', '0004_auto_20211107_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='number',
            field=models.IntegerField(blank=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='historicalcorrection',
            name='number',
            field=models.IntegerField(blank=True, verbose_name='Номер'),
        ),
    ]
