# Generated by Django 3.2.8 on 2021-11-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftn_national', '0006_auto_20211108_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correction',
            options={'ordering': ['-number'], 'verbose_name': 'Поправка', 'verbose_name_plural': 'Поправки'},
        ),
        migrations.AlterModelOptions(
            name='designatororg',
            options={'ordering': ['national'], 'verbose_name': 'Обозначение служб или предприятий', 'verbose_name_plural': 'Обозначение служб или предприятий'},
        ),
        migrations.AlterModelOptions(
            name='locationindicator',
            options={'ordering': ['national'], 'verbose_name': 'Обозначение местоположения', 'verbose_name_plural': 'Обозначение местоположения'},
        ),
        migrations.AlterModelOptions(
            name='symbolsdepartment',
            options={'ordering': ['national'], 'verbose_name': 'Обозначение подразделений', 'verbose_name_plural': 'Обозначение подразделений'},
        ),
        migrations.AlterField(
            model_name='correction',
            name='number',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='historicalcorrection',
            name='number',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='Номер'),
        ),
    ]
