# Generated by Django 3.2.8 on 2021-11-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftn_national', '0007_auto_20211114_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='aftn_message',
            field=models.TextField(blank=True, max_length=1800, verbose_name='Содержание поправки'),
        ),
        migrations.AlterField(
            model_name='historicalcorrection',
            name='aftn_message',
            field=models.TextField(blank=True, max_length=1800, verbose_name='Содержание поправки'),
        ),
    ]
