# Generated by Django 3.2.8 on 2021-11-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftn_national', '0008_auto_20211129_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocationindicator',
            name='district_administration',
            field=models.CharField(choices=[('ОУ ВТ ЦР', 'ОУ ВТ ЦР'), ('ЮЖН ОУ ВТ', 'ЮЖН ОУ ВТ'), ('ДВ ОУ ВТ', 'ДВ ОУ ВТ'), ('СЗ ОУ ВТ', 'СЗ ОУ ВТ'), ('ПРИВ ОУ ВТ', 'ПРИВ ОУ ВТ'), ('СИБ ОУ ВТ', 'СИБ ОУ ВТ'), ('УР ОУ ВТ', 'УР ОУ ВТ'), ('ФАВТ', 'ФАВТ'), ('----', '----')], default='----', max_length=10, verbose_name='Окружное управление ВТ'),
        ),
        migrations.AlterField(
            model_name='locationindicator',
            name='district_administration',
            field=models.CharField(choices=[('ОУ ВТ ЦР', 'ОУ ВТ ЦР'), ('ЮЖН ОУ ВТ', 'ЮЖН ОУ ВТ'), ('ДВ ОУ ВТ', 'ДВ ОУ ВТ'), ('СЗ ОУ ВТ', 'СЗ ОУ ВТ'), ('ПРИВ ОУ ВТ', 'ПРИВ ОУ ВТ'), ('СИБ ОУ ВТ', 'СИБ ОУ ВТ'), ('УР ОУ ВТ', 'УР ОУ ВТ'), ('ФАВТ', 'ФАВТ'), ('----', '----')], default='----', max_length=10, verbose_name='Окружное управление ВТ'),
        ),
    ]
