# Generated by Django 3.2.8 on 2021-12-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftn_national', '0009_auto_20211130_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(max_length=50, verbose_name='Database name')),
                ('user', models.CharField(max_length=50, verbose_name='User name used to authenticate')),
                ('password', models.CharField(max_length=50, verbose_name='Password used to authenticate')),
                ('host', models.GenericIPAddressField(protocol='IPv4', verbose_name='Database host address')),
                ('port', models.IntegerField(verbose_name='Connection port number')),
            ],
            options={
                'verbose_name': 'Server CKS',
                'verbose_name_plural': 'Servers CKS',
            },
        ),
    ]
